# Generated by Django 5.1.1 on 2024-10-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_restaurantimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant_additional_images/"
            ),
        ),
    ]
