# Generated by Django 5.1.1 on 2024-11-20 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_chosenfood"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Thread_comment",
        ),
        migrations.AddField(
            model_name="thread",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="thread_images/"),
        ),
    ]
