# Generated by Django 5.1.1 on 2024-12-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_thread_comment_thread_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="food",
            name="category",
        ),
        migrations.DeleteModel(
            name="SubCategory",
        ),
        migrations.AddField(
            model_name="food",
            name="category",
            field=models.ManyToManyField(related_name="foods", to="core.category"),
        ),
    ]
