# Generated by Django 5.1.1 on 2024-12-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_likedislikefood_delete_chosenfood"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="restaurant",
            name="categories",
            field=models.ManyToManyField(
                related_name="restaurants", to="core.restaurantcategory"
            ),
        ),
    ]
