# Generated by Django 5.1.1 on 2024-12-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_forumcomment_delete_forum_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
