# Generated by Django 5.1.1 on 2025-01-25 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_food_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="saved_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="saved_restaurants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
