# Generated by Django 5.1.1 on 2025-01-27 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_restaurant_saved_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="saved_by",
            field=models.ManyToManyField(
                blank=True, related_name="saved_forums", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
