# Generated by Django 5.1.1 on 2025-02-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_forum_saved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
