# Generated by Django 5.1.1 on 2025-02-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_restaurant_latitude_restaurant_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
