# Generated by Django 5.1.1 on 2025-02-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_profile_latitude_profile_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="location",
            field=models.TextField(max_length=255),
        ),
    ]
