# Generated by Django 5.1.1 on 2025-02-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_restaurant_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="likedislikefood",
            name="source",
            field=models.CharField(
                choices=[("random", "Random"), ("recommend", "Recommend")],
                default="random",
                max_length=20,
            ),
        ),
    ]
